env:
  global:
    - CC_TEST_REPORTER_ID=ae38241d281784c88a8d180f8068283083462148da4ee924f9e72c723ae7a332
language: node_js
node_js:
  - "0.10"
before_install:
  - npm install
  - npm install -g grunt-cli
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - grunt test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
