env:
  global:
    - CODECLIMATE_REPO_TOKEN=ae38241d281784c88a8d180f8068283083462148da4ee924f9e72c723ae7a332
language: node_js
node_js:
  - "0.10"
before_install:
  - npm install
  - npm install -g grunt-cli
script:
  - grunt test:coverage
after_script:
  - codeclimate-test-reporter < bin/coverage/lcov/lcov.info
